FROM python:3.6

RUN apt install git -y \
  && git clone https://github.com/sparrow-platform/disease-diagnostics-engine.git 


WORKDIR /disease-diagnostics-engine

ADD /umls.db /disease-diagnostics-engine/umls/databases/umls.db

RUN ls

RUN pip install -r requirements.txt

RUN pip install gunicorn flask



CMD [ "gunicorn", "--workers=2", "--bind=0.0.0.0:5000", "app:app"]


