FROM ubuntu:latest

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip


RUN apt install git -y \
  && git clone https://github.com/sparrow-platform/disease-diagnostics-engine.git 


WORKDIR /disease-diagnostics-engine

ADD /umls.db /disease-diagnostics-engine/umls/databases/umls.db

RUN ls

RUN pip install -r requirements.txt


CMD [ "gunicorn", "--workers=2", "--bind=0.0.0.0:5000", "server:app"]
