FROM python:3.6

RUN apt install git -y \
  && git clone https://github.com/sparrow-platform/disease-diagnostics-engine.git 


WORKDIR /disease-diagnostics-engine

ADD /umls.db /disease-diagnostics-engine/umls/databases/umls.db

RUN ls

ADD /requirements.txt /disease-diagnostics-engine/requirementsNew.txt
RUN pip install -r requirementsNew.txt

RUN pip install more-itertools

ADD /data /disease-diagnostics-engine/data/all-files-for-ml

ENTRYPOINT ["python"]
CMD ["app.py"]